sudo: false

language: node_js

node_js:
- '7'

env:
  global:
  - GIT_USER: ai-ot@travis
  - GIT_EMAIL: ai-ot@users.noreply.github.com
  - GH_REF: ai-ot/react-ja-date-picker

cache:
  yarn: true
  directories:
  - "~/.cache/yarn"

before_script:
- npm run build
- yarn global add codecov

script:
- npm run lint
- npm test
# - npm run coverage >/dev/null 2>&1
# - codecov

after_success:
- "openssl aes-256-cbc -K $encrypted_a136b2d89fef_key -iv $encrypted_a136b2d89fef_iv -in .travis_rsa.enc -out \"$HOME/.ssh/id_rsa\" -d"
- chmod 600 "$HOME/.ssh/id_rsa"
- npm run deploy:demo

deploy:
  provider: npm
  email: ai-ot@users.noreply.github.com
  api_key:
    secure: ei0jWQ7m2bl0wdcQpeYb2dn+Mslg+2sDK0Kk9++1qMaXsEM7a78cTXLegGTZDDDdda4UXnz3ct4ZlArnDVQYKk/4nidMfoH3AYJ8ynVX6SOy1Gr456xXehdGJO0zyhjkfJWEg0w7hP44E62B/h6JDX7qoEYmraLQo74jyf6pPc/NI4/zLz42YbqtxgC7UDr3In0aTsQMHY4HQXN8fs3deY3O8igvgp86Pa8ABM4Bgj9KZ0NIa6eVXadOzdCGQa4+DpjEeZB0NTsUm/oNu0oOYzNqAep6cs/dXl3qV+br+IouSVxZ3d3TtDeWsdSzFMxhRjtCjIhITJKjJTfi0HP88thhvzt4PeZTHNfsCUvDPwKU3I5xrngHrN6LkrIYvORelnjHYhU6j0ULzEl4swHy9dwWpfnbog7e6y7WnnUhs6L3RdoQsv9BZ7LYLPhxBkRKkIaRd8aLFBbv0Lj0U7nAUAN+18nVJqcbcIT5DzmTo7RgItWCieRdvmHJGS37b1EQaViigiuuOBzDA5LNynkPfJANcS5R02oKeptu0Xc5SNNWoJMVgXJdgbobbck6cRgwIww2LQ/dIpL0Qqb2+9Uxz0Mvjbn58Be/CJy+6mV4t51++y8CopBwqjW32hTlZoTcfSe7uCOYJ8jI+drm+2LzCRuYYaS56aCbHCoaN708KGE=
  on:
    tags: true
  skip_cleanup: true
